### ISSUE TITLE
zed-f9P ardusimple compatibility

### ISSUE THREAD

**Issue by smolleyes** [infusion/GPS.js#22] opened 2019-03-01 12:38 UTC
hi!

thanks for this library first it s great :)

So i have the new ardusimple board, i had to change few things to get it working with your lib (change gngga gst length... don t understand why) it works but still have few doubts on the results because of this (i receive data from bluetooth)

how can i get the speed and accuracy in the gps.state directly ? 

next step is to build an ntrip-client for rtk corrections! nothing in node/react-native for this incredible !!!

thanks

**Comment by smolleyes** [comment] 2019-03-01 13:35
only messages failing now

exemple:
Invalid GSV length: $GBGSV,1,1,00,*47

**Comment by infusion** [comment] 2019-03-01 13:45
Thanks! :) 
The GGA length works now? What did you change?
The GSV data does not look correct. The sentence should have the following entries: https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GSV.html

Is the NMEA data they send documented somewhere? I couldn't find it.

**Comment by smolleyes** [comment] 2019-03-01 13:59
hello

just replaces my file with your 0.50, i m listing all the errors

it s strange like i have one more coma in each messages... very strange

look:

 $GAGSV,3,3,09,33,11,027,,7*4F
 $GPGSV,3,1,12,06,05,097,,10,16,272,,12,70,239,41,13,01,152,,1*65
$GNRMC,134239.00,A,4843.01031,N,00227.79057,E,0.083,,010319,,,A,V*18
$GNGSA,A,3,24,15,17,12,32,25,19,,,,,,1.18,0.61,1.01,1*07

none of those messages works without changes

**Comment by smolleyes** [comment] 2019-03-01 14:02
look here:

https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf

:)

**Comment by smolleyes** [comment] 2019-03-01 14:56
definitly some problems with GSV messages

satsActive: (6) [24, 8, 25, 11, 2, 3]
satsVisible: []

**Comment by smolleyes** [comment] 2019-03-01 15:02
log on gst and str from your code:

(22) ["GSV", "3", "1", "11", "02", "20", "106", "26", "06", "20", "072", "18", "12", "77", "040", "37", "14", "30", "309", "25", "1", "65"] 

"$GPGSV,3,1,11,02,20,106,26,06,20,072,18,12,77,040,37,14,30,309,25,1*65"

**Comment by smolleyes** [comment] 2019-03-01 15:11
more data (all gsv types, i excluded gbgsv)

(22) ["GSV", "3", "1", "12", "02", "22", "103", "", "03", "00", "357", "", "06", "21", "068", "18", "12", "73", "046", "32", "6", "66"] "$GPGSV,3,1,12,02,22,103,,03,00,357,,06,21,068,18,12,73,046,32,6*66"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "2", "12", "14", "32", "306", "", "19", "16", "040", "", "22", "00", "338", "", "24", "42", "130", "30", "6", "62"] "$GPGSV,3,2,12,14,32,306,,19,16,040,,22,00,338,,24,42,130,30,6*62"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "3", "12", "25", "63", "270", "31", "29", "27", "193", "22", "31", "06", "302", "", "32", "41", "287", "", "6", "6C"] "$GPGSV,3,3,12,25,63,270,31,29,27,193,22,31,06,302,,32,41,287,,6*6C"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "1", "09", "65", "10", "228", "08", "66", "29", "288", "19", "67", "14", "341", "", "74", "26", "091", "24", "1", "7B"] "$GLGSV,3,1,09,65,10,228,08,66,29,288,19,67,14,341,,74,26,091,24,1*7B"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "2", "09", "75", "71", "024", "18", "76", "41", "304", "35", "84", "35", "041", "09", "85", "50", "122", "43", "1", "76"] "$GLGSV,3,2,09,75,71,024,18,76,41,304,35,84,35,041,09,85,50,122,43,1*76"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (10) ["GSV", "3", "3", "09", "86", "11", "171", "19", "1", "40"] "$GLGSV,3,3,09,86,11,171,19,1*40"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "1", "09", "65", "10", "228", "10", "66", "29", "288", "26", "67", "14", "341", "", "74", "26", "091", "09", "3", "73"] "$GLGSV,3,1,09,65,10,228,10,66,29,288,26,67,14,341,,74,26,091,09,3*73"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "2", "09", "75", "71", "024", "17", "76", "41", "304", "", "84", "35", "041", "09", "85", "50", "122", "39", "3", "70"] "$GLGSV,3,2,09,75,71,024,17,76,41,304,,84,35,041,09,85,50,122,39,3*70"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (10) ["GSV", "3", "3", "09", "86", "11", "171", "15", "3", "4E"] "$GLGSV,3,3,09,86,11,171,15,3*4E"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "1", "11", "02", "49", "285", "30", "03", "22", "221", "29", "07", "12", "328", "", "08", "32", "278", "35", "7", "74"] "$GAGSV,3,1,11,02,49,285,30,03,22,221,29,07,12,328,,08,32,278,35,7*74"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "2", "11", "11", "39", "108", "15", "12", "25", "046", "", "18", "39", "181", "47", "24", "19", "088", "18", "7", "7C"] "$GAGSV,3,2,11,11,39,108,15,12,25,046,,18,39,181,47,24,19,088,18,7*7C"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (18) ["GSV", "3", "3", "11", "25", "69", "065", "20", "30", "01", "275", "", "36", "16", "160", "25", "7", "4A"] "$GAGSV,3,3,11,25,69,065,20,30,01,275,,36,16,160,25,7*4A"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "1", "11", "02", "49", "285", "30", "03", "22", "221", "", "07", "12", "328", "", "08", "32", "278", "28", "2", "76"] "$GAGSV,3,1,11,02,49,285,30,03,22,221,,07,12,328,,08,32,278,28,2*76"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "3", "2", "11", "11", "39", "108", "24", "12", "25", "046", "", "18", "39", "181", "44", "24", "19", "088", "", "2", "71"] "$GAGSV,3,2,11,11,39,108,24,12,25,046,,18,39,181,44,24,19,088,,2*71"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (18) ["GSV", "3", "3", "11", "25", "69", "065", "34", "30", "01", "275", "", "36", "16", "160", "", "2", "4D"] "$GAGSV,3,3,11,25,69,065,34,30,01,275,,36,16,160,,2*4D"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "1", "1", "04", "13", "31", "064", "", "21", "12", "255", "", "26", "18", "293", "27", "29", "46", "155", "31", "1", "78"] "$GBGSV,1,1,04,13,31,064,,21,12,255,,26,18,293,27,29,46,155,31,1*78"
D:\projets\batexpert\mobibat\backup_rn_modules\gps\gps.js:488 (22) ["GSV", "1", "1", "04", "13", "31", "064", "", "21", "12", "255", "", "26", "18", "293", "", "29", "46", "155", "", "", "4E"] "$GBGSV,1,1,04,13,31,064,,21,12,255,,26,18,293,,29,46,155,,*4E"

**Comment by infusion** [comment] 2019-03-01 17:32
Okay, I fixed it. It was the addition of NMEA 4.10 in GSV, which was not handled correctly. Thanks a lot for opening this issue!
Could you test the current version on github? When it works out, I'll push it to npm

**Comment by smolleyes** [comment] 2019-03-01 18:01
heloo i ll try it brb !

**Comment by smolleyes** [comment] 2019-03-01 19:22
hello

it s ok for gsv but not closbale yet many other sentences fail

now it s 

$GNRMC,191029.00,A,4843.01033,N,00227.78756,E,0.024,,010319,,,A,V*1C
(ok if i add && rmc.length !== 15)

then
$GNGSA,A,3,25,29,31,26,16,21,,,,,,,1.55,0.84,1.30,1*00

gps.update received it as length = 20 ...

and it s ok but still some doubts on the satellites count

alt: 52.2
errors: 22
fix: "3D"
hdop: 0.87
lat: 48.71684116666667
lon: 2.4631393333333333
pdop: 1.8
processed: 76
satsActive: (2) [24, 26]
satsVisible: (11) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
speed: 0.033336
time: Fri Mar 01 2019 20:20:21 GMT+0100 (heure normale d’Europe centrale) {}
track: null
vdop: 1.57

do you cumulate each type of satellites?

THANKS !!

**Comment by infusion** [comment] 2019-03-02 12:20
Okay, RMC and GSA got new flags in 4.10 as well. Could you pleas test the latest version from github?

Sats active is overwritten with each new GSA. Sats visible is merged with every GSV chain. Given your example "$GNGSA,A,3,25,29,31,26,16,21,,,,,,,1.55,0.84,1.30,1*00", the output was wrong with satsActive: (2) [24, 26]. I added it as test case and it gives 

```
[
      25,
      29,
      31,
      26,
      16,
      21
    ]
```
as expected.

**Comment by smolleyes** [comment] 2019-03-06 19:29
hi

sorry for the delay ! :)

still somes problems with GSA

```
Possible Unhandled Promise Rejection (id: 6):
Error: Invalid GSA length: $GNGSA,A,3,21,16,31,26,27,29,20,,,,,,1.46,0.86,1.18,1*0A
```

thanks !

**Comment by smolleyes** [comment] 2019-03-06 19:56
hi

sorry for the delay

just trying with u-center launched at the same time with ntrip enable

no more errors with the new version but 

satsActive: []
satsVisible: []


sometimes satsVisible is populated 

u-center report RTK float fix and like 12 sats active, in the gps.js state i have 3D fix and satActive seems now always empty

i ll send you some raw data if you want :) 

thanks!

**Comment by infusion** [comment] 2019-03-06 20:01
Yes, that would be helpful. Sounds really strange as every sentence is populated to the state object, as you can see in the source. But good to know that no errors are disturbing the process. Do you know of any message types that are used and not implemented by gps.js? I wrote the library with 3 different receivers and hoped to catch all typical anomalies - but far from it

**Comment by infusion** [comment] 2019-03-06 20:03
If you don't want to have your location data published here, write me a mail at the email you can find in the license or package.json

**Comment by smolleyes** [comment] 2019-03-06 20:10
ok i ll send you an email 👍 

i have some problem with FAA mode now it return F Oo can t find info on a F for FAA field... seems coming from RMC parsing... brb

**Comment by smolleyes** [comment] 2019-03-06 20:12
found

seems you miss R and F in the FAA case :)

`The Mode indicator is two or more characters, with the first and second defined for GPS and GLONASS. Further characters may be defined. For each system, the character can have a value (table may be incomplete):

N = Constellation not in use, or no valid fix

A = Autonomous (non-differential)

D = Differential mode

P = Precise (no degradation, like Selective Availability)

R = Real Time Kinematic

F = Float RTK

E = Estimated (dead reckoning) Mode

M = Manual Input Mode

S = Simulator Mode`

**Comment by infusion** [comment] 2019-03-06 21:52
Uhm, do you have a reference for those? Every reference I found only states the ones that ar implemented. Parts of those you mentioned are GGA fix quality indicators, see http://campar.in.tum.de/twiki/pub/Chair/NaviGpsDemon/nmea.html

**Comment by infusion** [comment] 2019-03-06 21:59
Ah got it.

**Comment by smolleyes** [comment] 2019-03-06 22:06
yup for rmc then all others faa are "wrong" and fix in the state too :), i ll send you raw data in few minutes , thanks !

**Comment by infusion** [comment] 2019-03-06 22:31
Okay, fixed it in the last commit. This does not explain why you don't get satellites

**Comment by smolleyes** [comment] 2019-03-07 11:11
hello !

yup ok for the F/R still strange satActive count i know for the weird bytes i don t know wich message cause this.... why don t you make an object of satellites like satellites: { GP: [...], GA:[...], GL[...], GB[...]} just if we need details since active sats is directly printed in the GGA messages (for my device)

`age: null
alt: 63.6
geoidal: 46.3
hdop: 0.93
lat: 48.
lon: 2.
quality: "fix"
raw: "$GNGGA,110921.00,4843.00623,N,00227.78733,E,1,12,0.93,63.6,M,46.3,M,,*70"
satellites: 12`


still have a looot of errors in the sate error count how can i check them ?

**Comment by smolleyes** [comment] 2019-03-07 11:26
added some debug on rejetec lines:

`rejected  $GNGRS,112423.00,1,-0.1,-0.4,5.6,-4.3,1.4,-0.2,,,,,,,1,1*51
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNGRS,112423.00,1,0.0,0.0,0.0,-6.4,-1.2,,,,,,,,1,6*7F
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNGRS,112423.00,1,-2.5,0.8,0.2,7.2,6.2,,,,,,,,2,1*5B
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNGRS,112423.00,1,-0.4,0.5,4.5,0.0,4.9,,,,,,,,2,3*58
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNGRS,112423.00,1,-0.4,0.6,2.7,4.9,,,,,,,,,3,7*74
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNGRS,112423.00,1,-0.3,-0.5,-8.2,0.0,,,,,,,,,3,2*77
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNGRS,112423.00,1,-7.8,-9.3,,,,,,,,,,,4,1*57
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNGRS,112423.00,1,,,,,,,,,,,,,4,*63
rejected  $GNGBS,112423.00,2.5,1.5,5.5,,,,,,*5B
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNVLW,,N,,N,0.000,N,0.000,N*44
rejected  $GNGBS,112424.00,2.5,1.5,5.4,,,,,,*5D
D:\projets\batexpert\mobibat\node_modules\gps\gps.js:758 rejected  $GNVLW,,N,,N,0.000,N,0.000,N*44`

**Comment by infusion** [comment] 2019-03-07 11:30
Hi :)
do you need the FAA on the state object as well?
I think the errors come from the weird bytes. The error counter is incremented as soon as the `update` method fails. You could add a `console.log()` to each `return false` in the update method and check what bytes cause the error.
I wanted to abstract over the message types. This is why I'm not in favor of a state object that holds individual types. The active satellites array on the state object comes from GSA and the visible satellites array comes from GSV.  If you want to pick it yourself, you can easily subscribe to either

``on('data', data => console.log(data.type == 'GGA' ? data.satellites : null)``

or individually

``on('GGA', data => console.log(data. satellites))``

Ahh, the errors you experiencing come from message types that are not implemented yet. I will add them :)

**Comment by smolleyes** [comment] 2019-03-07 11:34
i know don t worry i just give you most information i can to get your library better :)

once done i ll fork it then send PR if needed :)

i want to have rtk float/fix in the state most important (will try now)

**Comment by infusion** [comment] 2019-03-07 11:35
I'm working on the missing types already. Give me 15min

**Comment by smolleyes** [comment] 2019-03-07 11:35
not interested to push it then implement a ntrip client to get rtk corrections ? your project can get to a new level with this (and market is empty for things like that in node/react/react-native)

**Comment by smolleyes** [comment] 2019-03-07 11:36
> I'm working on the missing types already. Give me 15min

take your time no stress :p

**Comment by infusion** [comment] 2019-03-07 12:00
Okay, check out latest commit :)

**Comment by infusion** [comment] 2019-03-07 12:02
You are more than welcome to add a ntrip client :)

**Comment by smolleyes** [comment] 2019-03-07 12:09
eheh this is my final goal to finish my DIY project :) i ll try, brb, thanks !

**Comment by infusion** [comment] 2019-03-07 12:11
May I ask what you're building where you need high precision?

**Comment by smolleyes** [comment] 2019-03-07 12:27
i work for an asbestos diagnostic company we need to report exactly where we make holes in the roads ... :) so i need rtk, i builded it thru this new ardusimple board, made the case myself, designed and printed it in 3d, react-native app to get the bluetooth serial then your lib to parse sentences... last step is the ntrip and i m done 100% :D i learned a LOTTT of things in this project

lastest version ok no more rejections, cool !

but 

alt: 74.9
errors: 24
fix: "3D"
hdop: 2.7
lat: 48
lon: 2.
pdop: 5.29
processed: 492
satsActive: [] /// **still empty i ll make some test with the state to help**
satsVisible: (9) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
speed: 0.079636
time: Thu Mar 07 2019 13:16:08 GMT+0100 (heure normale d’Europe centrale) {}
track: null
vdop: 4.55

i m struggling to get rtk position today thru u-center, strange....

**Comment by infusion** [comment] 2019-03-07 12:53
That sounds pretty awesome!

About the still empty active sats array: Was a GSA message already seen? Could you monitor the type together with the state like so:

```
on('data', data => console.log(data.type, GPS.state));
```

To see when a GSA came in and if it fails to bring up the satellites?

**Comment by smolleyes** [comment] 2019-03-07 13:38
just trying

`gps.on('data', e => {
      //console.log(e)
      if(e.raw.match(/GSA/)) {
        console.log(e.raw,gps.state)
      }`

`
$GNGSA,A,3,24,12,19,15,,,,,,,,,5.27,3.57,3.87,1*05 

alt: 55.5
errors: 7
fix: "3D"
hdop: 3.57
lat: 48
lon: 2.
pdop: 5.27
processed: 211
satsActive: []
satsVisible: (6) [{…}, {…}, {…}, {…}, {…}, {…}]
speed: 1.100088
time: Thu Mar 07 2019 14:32:15 GMT+0100 (heure normale d’Europe centrale) {}
track: null
vdop: 3.88
`

and still sometimes have:

REJECTED: $GNGNS,133216.00,4843.01093,N,00227.78866,E,ANNN,04,3.57,55.4,46.3,,,V*29

**Comment by infusion** [comment] 2019-03-07 13:47
I'll implement GNS. For your example:

```
var gps = new GPS;
gps.on('data', e => {
  console.log(e.raw, gps.state)
});
gps.update('$GNGSA,A,3,24,12,19,15,,,,,,,,,5.27,3.57,3.87,1*05');
```
gives
```
$GNGSA,A,3,24,12,19,15,,,,,,,,,5.27,3.57,3.87,1*05 { errors: 0,
  processed: 1,
  satsActive: [ 24, 12, 19, 15 ],
  fix: '3D',
  hdop: 3.57,
  pdop: 5.27,
  vdop: 3.87 }
```
As expected. What do you do differently?

**Comment by smolleyes** [comment] 2019-03-07 14:08
i don t see rmc messayes anymore strange maybe because i m not in Rtk... searching

just sended an email

**Comment by infusion** [comment] 2019-03-07 14:26
See last commit, minor changes and GNS was added.

**Comment by smolleyes** [comment] 2019-03-07 14:31
ok i ll try :)

strangely seems i receive GSA like by three... first seems ok 2 others no::

$GNGSA,A,3,72,74,82,83,73,71,,,,,,,3.32,1.81,2.78,2*00 {errors: 7, processed: 244, satsVisible: Array(0), time: Thu Mar 07 2019 15:26:02 GMT+0100 (heure normale d’Europe centrale), lat: 48.716807333333335, …}
D:\projets\batexpert\mobibat\src\components\bluetooth\index.js:124 $GNGSA,A,3,,,,,,,,,,,,,3.32,1.81,2.78,3*04 {errors: 7, processed: 245, satsVisible: Array(0), time: Thu Mar 07 2019 15:26:02 GMT+0100 (heure normale d’Europe centrale), lat: 48.716807333333335, …}
D:\projets\batexpert\mobibat\src\components\bluetooth\index.js:124 $GNGSA,A,3,,,,,,,,,,,,,3.32,1.81,2.78,4*03 {errors: 7, processed: 246, satsVisible: Array(0), time: Thu Mar 07 2019 15:26:02 GMT+0100 (heure normale d’Europe centrale), lat: 48.716807333333335, …}

**Comment by infusion** [comment] 2019-03-07 14:33
Based on the debug log you sent, the code of gps.js works just fine. For whatever reason you get GSA sentences with an empty satellite list, which of course resets the state. This is not cool :( We could add a test if the sats are empty and ignore it then. But what if the list is truly empty? Then the state has artifacts of old satellites hanging around forever.

**Comment by smolleyes** [comment] 2019-03-07 14:34
yup think the same thing, just updated the firmware of the zed-f9p same problem

**Comment by smolleyes** [comment] 2019-03-07 14:36
maybe check the number of GSA sentences .. if more than x messages in x time then keep First sentence of this last group of message... something like this maybe?

**Comment by infusion** [comment] 2019-03-07 14:37
"$GNGSA,A,3,72,74,82,83,73,71,,,,,,,3.32,1.81,2.78,200" -> does not look like a complete sentence.

**Comment by smolleyes** [comment] 2019-03-07 14:39
in u-blox text console,...

$GNVTG,,T,,M,0.021,N,0.040,K,D*3F
14:38:32  $GNGGA,143832.00,4843.00925,N,00227.78614,E,5,11,2.33,59.4,M,46.3,M,1.0,1702*57
14:38:32  $GNGSA,A,3,12,24,25,32,29,,,,,,,,5.13,2.33,4.57,1*0A
14:38:32  $GNGSA,A,3,72,74,82,83,73,71,,,,,,,5.13,2.33,4.57,2*04
14:38:32  $GNGSA,A,3,,,,,,,,,,,,,5.13,2.33,4.57,3*00
14:38:32  $GNGSA,A,3,,,,,,,,,,,,,5.13,2.33,4.57,4*07

**Comment by infusion** [comment] 2019-03-07 14:39
Either you have problems with your wiring that corrupt sentences are bashing in, or the receiver/firmware is buggy.

**Comment by smolleyes** [comment] 2019-03-07 14:40
yeah that s what i try to understand, in u-center data come directly from usb so nothing betweenn and i have those series of gsa messages

**Comment by infusion** [comment] 2019-03-07 14:40
Sorry, Github ate the * . So it might be correct

**Comment by smolleyes** [comment] 2019-03-07 14:42
> Sorry, Github ate the * . So it might be correct

eheh yes... just sended anoter email with all data from u-center and usb directly....

**Comment by infusion** [comment] 2019-03-07 14:43
No worries, the GSA is correct you sent. But why do you expect the sats **visible** to be updated with GSA?

**Comment by smolleyes** [comment] 2019-03-07 14:44
ah no i just speak about the activesats

**Comment by smolleyes** [comment] 2019-03-07 14:44
trying the lastest version now

**Comment by smolleyes** [comment] 2019-03-07 14:47
allright 0 errors in state now, sat in views = 12 active stats = 0 lol normal.... will try to find why, brb

**Comment by infusion** [comment] 2019-03-07 14:58
I parsed your whole dump and found another little error. Your receiver sends GSV messages even with empty set of sats. Check out the latest. But still it is a problem how to cope with empty arrays. I'm not in favor changing the behavior of the state in the way you proposed it. What I could think of is a config option to ignore empty sats, for visible and active sats.

**Comment by smolleyes** [comment] 2019-03-07 15:00
yup but i try to understand what s happening at the device level first don t understand why it send everything by 4 ... all messages have 4 lines with different values but same type Oo

**Comment by smolleyes** [comment] 2019-03-07 15:02
so how GSV and GSA are sended is the problem now not the library :)

**Comment by infusion** [comment] 2019-03-07 15:06
I mean, you could ask the manufacturer to not send empty sats in their firmware. They are a kickstarter project, so chances are you get contact

**Comment by smolleyes** [comment] 2019-03-07 15:13
this chip is from u-blox :)

**Comment by smolleyes** [comment] 2019-03-07 15:47
hummm not the only one:

https://lists.gnu.org/archive/html/gpsd-users/2016-04/msg00007.html

**Comment by smolleyes** [comment] 2019-03-07 16:33
possible to link the GGA quality to the state fix type ? or i ll do it in my code, fix say 3D when i m in rtk float (reported correctly by GGA parsing) :)

**Comment by smolleyes** [comment] 2019-03-08 01:02
ok i ll fix my problems you can close the issue since the lib works fine ! :)

do you know how to calculate the accuracy in meters, i m searching... (and hate maths lol) ?

**Comment by infusion** [comment] 2019-03-08 01:34
The simple answer is: If the receiver would know the error, it would be possible to correct for it.

The medium answer is: Create a regression problem with the three HDOP, PDOP, VDOP values and find statistically values for x, y and z so that your error is `x*HDOP + y*PDOP + z*VDOP`. This is probably less useful as the DOP value does not say much about quality of the signal but what constellation of satellites is used for calculations.

The hard answer is: You don't like math, but a reliable Estimated Position Error can only be found with math and a proper amount of samples. I would go with a Kalman filter (I published the npm "kalman" package for it). Simply said, a Kalman filter builds up an idea (a model) of where you are plus a Gaussian distributed error (with it you can calculate meters) by incorporating new measurements. Understanding the filter is math heavy and takes more than 2 minutes. If you're not satisfied with the first two answers, I can set up the KF for gps.js.

**Comment by smolleyes** [comment] 2019-03-08 01:43
can t believe that was so hard to "just" print an estimated accuracy !

thanks for the lesson professor :), i now understand the principle but i think this part is definitely not for me...

if you can implement it, not for me and not to satisfy me but, just to get your library better so yes it could be a nice update :)

**Comment by infusion** [comment] 2019-03-08 09:57
Yea, unfortunately this is problem is not so trivial. But the side effect of the KF is, you get a better estimate of where you are. The GPS coordinate can jump a few meters - which is nevertheless incredible good when you imagine that a satellite has a speed of 10000Km/h and new satellites surface from the horizon and vanish on the other side very quickly.
I will implement it over the course of the day.

**Comment by smolleyes** [comment] 2019-03-08 11:57
Hi m8

Thanks for your great work! Good luck with this! I forked your repo to make
changes specific to me :)

Le ven. 8 mars 2019 à 10:57, Robert Eisele <notifications@github.com> a
écrit :

**Comment by infusion** [comment] 2019-03-08 16:16
I decided against the addition of the filter to the main gps file, rather I added it to the maps example. I will push it in a few minutes. It looks like this now:

![image](https://user-images.githubusercontent.com/197742/54040510-d5a16e00-41c5-11e9-8072-dd065d7f1a6e.png)

**Comment by infusion** [comment] 2019-03-09 00:28
I pushed the code. Only thing you have to do is using the kalman library and copy and paste the matrix definitions and feed the update method. After the update you can use `filter.x` which is a 2-element array of the best estimate of the latitute and longitude. And on top of that you have `filter.P` which is a 2x2-element array, where you simply can use the diagonal elements `filter.P[0][0]` and `filter.P[1][1]` as an error estimate, where the first is the error in degree of the latitude and the second the error in degree in longitude. I think the easiest would be to use the haversine distance formula for two geo-points and calculate the distance between `filter.x[0] - sqrt(filter.P[0][0])` and `filter.x[0] + sqrt(filter.P[0][0])` and the same for the longitude. 
Note that for `var R = Sylvester.Matrix.I(2).multiply(0.00001);` the 0.00001 value is the accuracy of your GPS receiver from which the accuracy of your result depends. Good luck with that :)

**Closed by infusion** 2019-03-09 00:28 UTC
